import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About/About'
import Header from '../components/Header/Header'
import HeaderContent from '../components/Header/HeaderContent'
import styles from '../styles/Home.module.scss'
import aboutStyle from '../styles/About.module.scss'
import Advantages from '../components/Advantages/Advantages'
import Products from '../components/Products/Products'

import SvgProd from '../public/img/prodSvg.svg';
import SvgProdBlack from '../public/img/prodBlack.svg';
import Reviews from '../components/Reviews/Reviews'
import Contacts from '../components/Contacts/Contacts'
import Slide from '../components/Header/Slide'

export default function Home() {
  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet"></link>
      </Head>

      <header className={styles.header}>
          <Header />
          <div className={styles.header_line}></div>
          <HeaderContent />
      </header>
      <section className={aboutStyle.about}>
          <About />
      </section>
      <section>
        <Advantages />
      </section>
      <section>
        <Products id={'ibutamoren'} img="/img/products/Group 24.png" svg={SvgProd} title='PRODUCTS' name='IBUTAMOREN' text='Ibutamoren (also known as MK-677) is a potent, synthetic, long-acting, orally-active, selective, 
                  and non-peptide agonist of the Ghrelin receptor, Ghrelin mimetic and a Growth hormone secretagogue. 
                  Ibutamoren has chemical formula C27H36N4O5S and molar mass 528.662 g/mol. The elimination half-life of 
                  Ibutamoren is approximately 
                  4-6 hours, but IGF-1 levels in humans remain elevated at a single oral dose of up to 24 hours'/>
        <Products id={'ligandrol'}  img="/img/products/Group 30.png" svg={SvgProdBlack} white="white" name='LIGANDROL' text='LGD-4033 (often also called as Ligandrol) is a oral, nonsteroidal and potent selective androgen receptor modulator (SARM). It was developed to increase anabolic activity and reduce muscle wasting in people with severe diseases associated with catabolic conditions and critical loss of muscle mass. In clinical trials, LGD-4033 has 
                  shown significant anabolic activity in muscles and antiresorptive and anabolic activity in bones.'/>
        <Products id={'realmass'}  img="/img/products/Group 26.png" svg={SvgProd} name='REAL MASS' text='Real Mass by 50 BMG Pharm No Added Sugar is a natural flavor and high nutrient content to help you increase your calorie intake and gain weight quickly. It provides balanced nutrition and nutrition, and does not contain any stimulants or steroids.'/>
        
        <Products id={'realslim'}  img="/img/products/Group 25.png" svg={SvgProdBlack} white="white" name='REAL SLIM' text='Real Slim compares favorably with any preparations of a similar effect with its herbal composition, high efficiency and the ability to have a beneficial effect on the body. With the help of these tablets, you can get rid of 10 extra pounds in 1 course of admission, at the same time remove toxins with toxins, correct the figure in problem areas, improve skin condition, improve metabolism, and activate fat breakdown.'/>
        
        
        <Products id={'sleeptight'}  img="/img/products/Group 28.png" svg={SvgProd} name='SLEEP TIGHT' text='Sleep Tight contains natural, non-addictive substances that effectively increase serotonin levels. These include 5HTP and L-theanine, as well as a number of herbs that promote serotonin production. The herbs that make up Sleep Tight have long been used in herbal medicine as sedatives and hypnotics. Science has recently confirmed the validity of this traditional approach.'/>
        <Products id={'realtribulus'}  img="/img/products/Group 29.png" svg={SvgProdBlack} white="white" name='REAL TRIBULUS' text='Tribulus Terrestris plant extract is the most powerful and effective non-hormonal drug for enhancing potency, libido (sexual desire), as well as a remedy for male infertility. In oriental medicine, this herb is known as a very effective kidney tonic. Numerous clinical trials have confirmed the high efficiency of the drug in the treatment of various types of impotence, enhancing libido and orgasmic sensations.'/>
        <Products id={'testorampage'}  img="/img/products/Group 27.png" svg={SvgProd} name='TESTO-RAMPAGE' text='Testo-Rampage is a natural testosterone boosting formula composed of minerals and vitamins. Compared to most testosterone supplements on the market, this formula contains no harmful synthetic ingredients. According to the official website, the supplement is made using advanced technology to naturally increase testosterone levels in the body.'/>
      </section>
      <section>
        <Reviews />
      </section>
      <footer>
        <Contacts/>
      </footer>
    </div>
  )
}
